### ISSUE TITLE
Compose File snippet convert

### ISSUE THREAD

**Issue by MSBlueVn** [composerize/composerize#559]
**Do you want to request a *feature* or report a *bug*?**

- [X] feature request
- [ ] bug report

Hello, love this service, I was wondering if there's a chance this could get updated to also convert snippets from the old docker compose files to the newest format of Compose V2.

The same function “docker compose convert” does, only for snippets.

I.E., I have a snippet I found on the web that looks like this:
services:
 application:
  dns:
   - 8.8.8.8
   - 4.4.4.4
   - 192.168.9.45
 
And I want that converted to the new format, so it would fit with my up to date compose file.

Is that possible?

**Comment by sharevb** [comment]
Hi @MSBlueVn, as far as I read, there is not so much differences from version: 2 to version:3

**Comment by sharevb** [comment]
Probably will just add an option to set version: xxx

**Comment by MSBlueVn** [comment]
Hey and thanks for writing back, it's not V2 vs. v3 as shown in the version on top of the docker file. That's still the V1 method. When I meant V2, I meant this:
https://docs.docker.com/compose/migrate/
And as mentioned, when you run docker compose convert of a yml file, that converts it to V2.

**Comment by sharevb** [comment]
Hi, could also be this guide : https://docs.docker.com/compose/compose-file/compose-versioning/

By the way, if you have link to samples, some gist or compose files, please Can you provide here ? thanks

**Comment by MSBlueVn** [comment]
![image](https://github.com/magicmark/composerize/assets/100758741/dd1913bf-96c5-40a6-a1a8-6853ce313ed7)
I can generate a file example if you wish.

**Comment by MSBlueVn** [comment]
### **Original compose:**
```
version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
  db-data:
```

### **Converted file:**
```
name: untitledfolder
services:
  db:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: postgres:9.4
    networks:
      backend: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data
      volume: {}
  redis:
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    image: redis:alpine
    networks:
      frontend: null
    ports:
    - mode: ingress
      target: 6379
      protocol: tcp
  result:
    depends_on:
      db:
        condition: service_started
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    image: dockersamples/examplevotingapp_result:before
    networks:
      backend: null
    ports:
    - mode: ingress
      target: 80
      published: "5001"
      protocol: tcp
  visualizer:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: dockersamples/visualizer:stable
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    stop_grace_period: 1m30s
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
  vote:
    depends_on:
      redis:
        condition: service_started
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
    image: dockersamples/examplevotingapp_vote:before
    networks:
      frontend: null
    ports:
    - mode: ingress
      target: 80
      published: "5000"
      protocol: tcp
  worker:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        APP: VOTING
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 2m0s
      placement:
        constraints:
        - node.role == manager
    image: dockersamples/examplevotingapp_worker
    networks:
      backend: null
      frontend: null
networks:
  backend:
    name: untitledfolder_backend
  default:
    name: untitledfolder_default
  frontend:
    name: untitledfolder_frontend
volumes:
  db-data:
    name: untitledfolder_db-data
```
