### ISSUE TITLE
--log-opt's not converted to an object

### ISSUE THREAD

**Issue by frankhommers** [composerize/composerize#574]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [X] bug report

**Please provide a sample input docker run command**
```
docker run \     --log-driver json-file \     --log-opt max-size=10m \     --log-opt max-file=10 \     alpine echo hello world
```

**What is the current output?***
```
version: '3.3'
services:
    world:
        logging:
            driver:
                - json-file
            options: 'max-size=10m,max-file=10'
        image: world
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    world:
        logging:
            driver: "json-file"
            options: 
                max-size: "10m"
                max-file: "10"             
        image: world
```

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
