### ISSUE TITLE
The --net and --log-driver generates errors when using docker compose

### ISSUE THREAD

**Issue by paulvirtuel** [composerize/composerize#582]
**Do you want to request a *feature* or report a *bug*?**

- [x] bug report

**Please provide a sample input docker run command**
```
docker run -td --rm -p 80:80 --net=my_network --log-driver=journald --stop-signal=SIGRTMIN+3 --name my_container my_image
```

**What is the current output?***
```
name: <your project name>
services:
    my_image:
        tty: true
        ports:
            - 80:80
        networks:
            - my_network
        logging:
            driver:
                - journald
        stop_signal: SIGRTMIN+3
        container_name: my_container
        image: my_image
networks:
    my_network:
        external:
            name: my_network
```

**What is the expected/desired output?**
```
name: <your project name>
services:
    my_image:
        tty: true
        ports:
            - 80:80
        networks:
            - my_network
        logging:
            driver: journald
        stop_signal: SIGRTMIN+3
        container_name: my_container
        image: my_image
networks:
    my_network:
        external: true
```

**Are you willing/able to attempt a fix?**

Sorry, I looked at the source code, but I am not familiar enough with the code to attempt a fix.

Thanks for making this great tool!
