### ISSUE TITLE
parameter with equal mark is not fully converted 

### ISSUE THREAD

**Issue by kula99** [composerize/composerize#638]
**Do you want to request a *feature* or report a *bug*?**

- [ ] feature request
- [x] bug report

**Please provide a sample input docker run command**
```
docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -e JAVA_OPTS="-Dfile.encoding=utf-8 -Dsun.jnu.encoding-utf-8" jenkins/jenkins:lts-jdk17
```

**What is the current output?***
```
name: <your project name>
services:
    jenkins:
        ports:
            - 8080:8080
            - 50000:50000
        restart: on-failure
        environment:
            - JAVA_OPTS="-Dfile.encoding
        image: jenkins/jenkins:lts-jdk17
```

**What is the expected/desired output?**
```
name: <your project name>
services:
    jenkins:
        ports:
            - 8080:8080
            - 50000:50000
        restart: on-failure
        environment:
            - JAVA_OPTS="-Dfile.encoding=utf-8 -Dsun.jnu.encoding-utf-8"
        image: jenkins/jenkins:lts-jdk17
```
It seems the value of `JAVA_OPTS` which contains equal mark is not converted properly

**Are you willing/able to attempt a fix?**

Most issues can be trivially addressed by updating this mapping: 

https://github.com/magicmark/composerize/blob/dcae8ace865e2eef69e5bd27c4a9a320f56cac75/packages/composerize/src/mappings.js#L62-L66

- [ ] Is this the case for your issue?
- [ ] Would you be able to try? :) 

Thanks for following this template and making composerize better for everyone else too!
