### ISSUE TITLE
Error when parcing run command in docker run 

### ISSUE THREAD

**Issue by StefanFilkov** [composerize/composerize#678]
this command:
```
docker run \
  -v <CONFIG_FILE_PATH>:/etc/alloy/config.alloy \
  -p 12345:12345 \
  grafana/alloy:latest \
    run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data \
    /etc/alloy/config.alloy
```

was composerized to this:
```
name: <your project name>
services:
    alloy:
        volumes:
            - <CONFIG_FILE_PATH>:/etc/alloy/config.alloy
        ports:
            - 12345:12345
        image: grafana/alloy:latest
        command: run --server.http.listen-addr=0.0.0.0:12345
            --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
volumes:
    <CONFIG_FILE_PATH>:
        external: true
        name: <CONFIG_FILE_PATH>
```
        
and should the command should be like this:
```
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
```

**Comment by sharevb** [comment]
Hi @StefanFilkov,

So it should be something like this (composerize will not handle multiline commands using >) :
```
name: <your project name>
services:
    alloy:
        volumes:
            - <CONFIG_FILE_PATH>:/etc/alloy/config.alloy
        ports:
            - 12345:12345
        image: grafana/alloy:latest
        command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
```
