### ISSUE TITLE
run comands that reference volumes with spaces break the conversion

### ISSUE THREAD

**Issue by jeremymeyers** [composerize/composerize#724]
My Navidrome container links to a local volume with a space in the name. Using [runlike](https://github.com/lavie/runlike) generated the following command

`docker run --name=navidrome --hostname=navidrome --mac-address=02:42:ac:11:00:02 --volume /volume1/homes/JEREMYMEYERS/Drive/Backup/Music Drive/P/Sound Files:/music --volume /volume1/docker/data/navidrome:/data --env=LastFM.ApiKey=e4edbec1291d9501c3714857a1f57b8 --env=LastFM.Secret=a7e51b2b1eec62db83cf219180bd8da --network=bridge --workdir=/app -p 4533:4533 --restart=always --log-driver=db --runtime=runc --detach=true -t deluan/navidrome:latest
`

Running it through Containerize.com leads to this result, which is borked.

```
version: "2.4"
services:
    Sound:
        container_name: navidrome
        hostname: navidrome
        mac_address: 02:42:ac:11:00:02
        volumes:
            - /volume1/homes/JEREMYMEYERS/Drive/Backup/Music
        image: Drive/P/Sound
        command: Files:/music --volume /volume1/docker/data/navidrome:/data
            --env=LastFM.ApiKey=[EDITED]
            --env=LastFM.Secret=[EDITED] --network=bridge
            --workdir=/app -p 4533:4533 --restart=always --log-driver=db
            --runtime=runc --detach=true -t deluan/navidrome:latest
```

It looks like the spaces in the volumes break the parsing altogether.
