### ISSUE TITLE
Issue with shell expressions in env vars

### ISSUE THREAD

**Issue by d-Rickyy-b** [composerize/composerize#744]
I tried to convert the following docker run command (taken from https://github.com/Ilshidur/tor-relay-docker, shortened for better readability). 
```bash
docker run \
  -d \
  --name tor-relay \
  -e TZ=Europe/London \
  -e PUID=$(id -u) \
  -e PGID=$(id -g) \
  -v $(pwd)/tor/data:/data:Z \
  -p 9001:9001 \
  --restart always \
  ilshidur/tor-relay
```

It created the following docker compose yaml:

```yaml
# ignored options for 'tor-relay'
# -)=true,true
# -g
name: <your project name>
services:
    tor-relay:
        container_name: tor-relay
        environment:
            - TZ=Europe/London
            - PUID=$(id
            - PGID=$(id
        user: "true"
        volumes:
            - $(pwd)/tor/data:/data:Z
        ports:
            - 9001:9001
            - 9030:9030
        restart: always
        image: ilshidur/tor-relay
```

The PUID and PGID env vars aren't handled properly. The expression in the `$()` isn't properly converted into the yaml format. I assume it interprets the -u from the bash expression as a `docker run` flag.

Interestingly, when using the following docker command even more breaks.

```bash
docker run \
  -d \
  --name tor-relay \
  -e TZ=Europe/London \
  -e PUID=$(id -u) \
  -e PGID=$(id -g) \
  ilshidur/tor-relay
```

Result:

```yaml
# ignored options for '!!!invalid!!!'
# -)=true,ilshidur/tor-relay
# -g
name: <your project name>
services:
    "!!!invalid!!!":
        container_name: tor-relay
        environment:
            - TZ=Europe/London
            - PUID=$(id
            - PGID=$(id
        user: "true"
```

Shell expressions in the compose file aren't supported by docker (see https://github.com/docker/compose/issues/4081), so obviously the user needs to change these anyway in order to get a valid compose file. But maybe they can be properly handled (or at least converted literally), so that the parsing of the rest of the run command isn't broken?
