### ISSUE TITLE
Mounting named volumes doesn’t work in docker-compose files

### ISSUE THREAD

**Issue by bggolding** [composerize/composerize#97]
I believe this is a bug.

When docker-compose tries to mount a named volume, by default it prepends the project’s name to the volume, ie, a named volume “nexus-data” will be mounted as “project_nexus-data”.  The direct docker command doesn’t prepend the project name so the two commands don’t access the same data.  To make docker-compose use the unmodified name, it needs to be marked as an external container and its name specified.

**Please provide a sample input docker run command**
```
docker run -d -p 8081:8081 -p 5000:5000 --name nexus --restart=always -v nexus-data:/nexus-data sonatype/nexus3
```

**What is the current output?***
```
version: '3.3'
services:
    nexus3:
        ports:
            - '8081:8081'
            - '5000:5000'
        container_name: nexus
        restart: always
        volumes:
            - 'nexus-data:/nexus-data'
        image: sonatype/nexus3
```

**What is the expected/desired output?**
```
version: '3.3'
services:
    nexus3:
        ports:
            - '8081:8081'
            - '5000:5000'
        container_name: nexus
        restart: always
        volumes:
            - 'nexus-data:/nexus-data'
        image: sonatype/nexus3

volumes:
    nexus-data:
        external:
            name: nexus-data
```
